name: Continuous Integration

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1, 8.2]
        laravel: [9.*, 10.*]
        dependency-version: [prefer-stable]

    name: CI - PHP ${{ matrix.php }}  - Laravel ${{ matrix.laravel }} (${{ matrix.dependency-version }})

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip
          coverage: pcov

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist --no-suggest
      - name: PHPUnit Testing
        run: vendor/bin/phpunit